apiVersion: v1
kind: Secret

metadata:
  name: shortener-secrets
  namespace: shortener

type: Opaque
stringData:
  database_url: "EXAMPLE URL"
  postgres_user: "EXAMPLE USER"
  postgres_password: "EXAMPLE PASSWORD"
  postgres_db: "EXAMPLE DB"