
name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  backend-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.25

    - name: Cache Go modules
      uses: actions/cache@v5
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    
    - name: Run unit test
      run: make test-unit
  
  backend-integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: shortener_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shortener
        options: >-
          --health-cmd "pg_isready -U shortener_user -d shortener"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.25
    
    - name: Cache Go modules
      uses: actions/cache@v5
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Run integration tests
      run: make test-integration
    
  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 25

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    
    - name: Cache pnpm store
      uses: actions/cache@v5
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
    
    - name: Install dependencies
      run: cd frontend && pnpm install --frozen-lockfile
    
    - name: Build
      run: cd frontend && pnpm build
